version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - /home/admin/web/ruby:/420on
      - gem_cache:/usr/local/bundle/gems:delegated
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      ruby_net:

  database:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql:delegated
    restart: always
    env_file: .env
    networks:
      ruby_net:

  redis:
    image: redis:6.0.4
    networks:
      ruby_net:

volumes:
  db_data:
  gem_cache:

networks:
  ruby_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "ruby_net"
