rvm:
  - 1.9.3
before_script:
  - "cp config/database.yml.ci config/database.yml"
  - "RAILS_ENV=test SKIP_SYNCHRONIZATION=1 bundle exec rake db:drop db:create db:structure:load db:migrate"
script: "RAILS_ENV=test bundle exec rake spec"
