420on.cz:
  "<!-- Яндекс.Директ -->
  <script type='text/javascript'>
  yandex_partner_id = 107636;
  yandex_site_bg_color = 'FFFFFF';
  yandex_site_charset = 'windows-1251';
  yandex_ad_format = 'direct';
  yandex_font_size = 1;
  yandex_direct_type = 'horizontal';
  yandex_direct_border_type = 'ad';
  yandex_direct_limit = 2;
  yandex_direct_title_font_size = 3;
  yandex_direct_border_radius = true;
  yandex_direct_header_bg_color = 'FEEAC7';
  yandex_direct_bg_color = 'FFF9F0';
  yandex_direct_border_color = 'FBE5C0';
  yandex_direct_title_color = '0000CC';
  yandex_direct_url_color = '006600';
  yandex_direct_text_color = '000000';
  yandex_direct_hover_color = '0066FF';
  yandex_direct_favicon = true;
  document.write('<sc'+'ript type=\"text/javascript\" src=\"http://an.yandex.ru/system/context.js\"></sc'+'ript>');
  </script>
  <script type='text/javascript'><!--
  google_ad_client = 'ca-pub-4497943945759666;
  /* Banner hlavnaya */
  google_ad_slot = '8871393607';
  google_ad_width = 468;
  google_ad_height = 60;
  //-->
  </script>
  <script type='text/javascript'
  src='http://pagead2.googlesyndication.com/pagead/show_ads.js'>
  </script>"
